apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: containers-cache-pvc
spec:
  resources:
    requests:
      storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  