apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-cloned-source-pvc
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  
