apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-pipeline
spec:
  params:
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: "master"
  workspaces:
    - name: local-maven-repo
    - name: git-cloned-source
    - name: containers-cache
  tasks:
  - name: git-clone
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: git-cloned-source
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: build-pet-clinic
    taskRef:
      name: mvn
    params:
    - name: GOALS
      value: 
        - "clean"
        - "install"
    workspaces:
    - name: maven-repo
      workspace: local-maven-repo
    - name: source
      workspace: git-cloned-source  
    runAfter:
    - git-clone
  