
apiVersion: template.openshift.io/v1 
kind: Template
metadata: 
  name: secret-template 
  annotations:
    description: "Create gitlab secret" 
objects:
- apiVersion: v1 
  kind: Secret 
  metadata: 
    name: gitlab-secret 
    annotations: 
      tekton.dev/git-0: ${GITLAB_URL} 
  type: kubernetes.io/basic-auth 
  stringData: 
    username: ${GITLAB_USERNAME} 
    password: ${GITLAB_TOKEN} 
parameters: 
- name: GITLAB_USERNAME 
  description: "Gitlab Username" 
  required: true 
- name: GITLAB_TOKEN 
  description: "Gitlab token" 
- name: GITLAB_URL 
  description: "GIT LAB URL" 
  value: https://gitlab.com/chrismathew
